/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsatRouteImport } from './routes/vsat'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DemoClassRouteImport } from './routes/demo-class'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminVsatRegistrationsRouteImport } from './routes/admin/vsat-registrations'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin/demo-requests'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminContactMessagesRouteImport } from './routes/admin/contact-messages'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CoursesClassSlugSubjectSlugRouteImport } from './routes/courses.$classSlug.$subjectSlug'
import { Route as AuthenticatedEnrollCourseIdRouteImport } from './routes/_authenticated/enroll.$courseId'
import { Route as AuthenticatedEnrollSuccessCourseIdRouteImport } from './routes/_authenticated/enroll-success.$courseId'
import { Route as AuthenticatedDashboardProgressRouteImport } from './routes/_authenticated/dashboard_.progress'

const VsatRoute = VsatRouteImport.update({
  id: '/vsat',
  path: '/vsat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClassRoute = DemoClassRouteImport.update({
  id: '/demo-class',
  path: '/demo-class',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVsatRegistrationsRoute = AdminVsatRegistrationsRouteImport.update({
  id: '/vsat-registrations',
  path: '/vsat-registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesClassSlugSubjectSlugRoute =
  CoursesClassSlugSubjectSlugRouteImport.update({
    id: '/courses/$classSlug/$subjectSlug',
    path: '/courses/$classSlug/$subjectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEnrollCourseIdRoute =
  AuthenticatedEnrollCourseIdRouteImport.update({
    id: '/enroll/$courseId',
    path: '/enroll/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnrollSuccessCourseIdRoute =
  AuthenticatedEnrollSuccessCourseIdRouteImport.update({
    id: '/enroll-success/$courseId',
    path: '/enroll-success/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProgressRoute =
  AuthenticatedDashboardProgressRouteImport.update({
    id: '/dashboard_/progress',
    path: '/dashboard/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/dashboard_/progress': typeof AuthenticatedDashboardProgressRoute
  '/_authenticated/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/_authenticated/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
    | '/dashboard/progress'
    | '/enroll-success/$courseId'
    | '/enroll/$courseId'
    | '/courses/$classSlug/$subjectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/courses/$slug'
    | '/admin'
    | '/courses'
    | '/dashboard/progress'
    | '/enroll-success/$courseId'
    | '/enroll/$courseId'
    | '/courses/$classSlug/$subjectSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
    | '/_authenticated/dashboard_/progress'
    | '/_authenticated/enroll-success/$courseId'
    | '/_authenticated/enroll/$courseId'
    | '/courses/$classSlug/$subjectSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DemoClassRoute: typeof DemoClassRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VsatRoute: typeof VsatRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesClassSlugSubjectSlugRoute: typeof CoursesClassSlugSubjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsat': {
      id: '/vsat'
      path: '/vsat'
      fullPath: '/vsat'
      preLoaderRoute: typeof VsatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-class': {
      id: '/demo-class'
      path: '/demo-class'
      fullPath: '/demo-class'
      preLoaderRoute: typeof DemoClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vsat-registrations': {
      id: '/admin/vsat-registrations'
      path: '/vsat-registrations'
      fullPath: '/admin/vsat-registrations'
      preLoaderRoute: typeof AdminVsatRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/$classSlug/$subjectSlug': {
      id: '/courses/$classSlug/$subjectSlug'
      path: '/courses/$classSlug/$subjectSlug'
      fullPath: '/courses/$classSlug/$subjectSlug'
      preLoaderRoute: typeof CoursesClassSlugSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enroll/$courseId': {
      id: '/_authenticated/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/enroll/$courseId'
      preLoaderRoute: typeof AuthenticatedEnrollCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enroll-success/$courseId': {
      id: '/_authenticated/enroll-success/$courseId'
      path: '/enroll-success/$courseId'
      fullPath: '/enroll-success/$courseId'
      preLoaderRoute: typeof AuthenticatedEnrollSuccessCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_/progress': {
      id: '/_authenticated/dashboard_/progress'
      path: '/dashboard/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof AuthenticatedDashboardProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDashboardProgressRoute: typeof AuthenticatedDashboardProgressRoute
  AuthenticatedEnrollSuccessCourseIdRoute: typeof AuthenticatedEnrollSuccessCourseIdRoute
  AuthenticatedEnrollCourseIdRoute: typeof AuthenticatedEnrollCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDashboardProgressRoute: AuthenticatedDashboardProgressRoute,
  AuthenticatedEnrollSuccessCourseIdRoute:
    AuthenticatedEnrollSuccessCourseIdRoute,
  AuthenticatedEnrollCourseIdRoute: AuthenticatedEnrollCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminVsatRegistrationsRoute: typeof AdminVsatRegistrationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminVsatRegistrationsRoute: AdminVsatRegistrationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DemoClassRoute: DemoClassRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VsatRoute: VsatRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesClassSlugSubjectSlugRoute: CoursesClassSlugSubjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
