/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsatRouteImport } from './routes/vsat'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DemoClassRouteImport } from './routes/demo-class'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminVsatRegistrationsRouteImport } from './routes/admin/vsat-registrations'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLiveClassesRouteImport } from './routes/admin/live-classes'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminFixLessonsRouteImport } from './routes/admin/fix-lessons'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin/demo-requests'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminContactMessagesRouteImport } from './routes/admin/contact-messages'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs.index'
import { Route as CoursesClassSlugSubjectSlugRouteImport } from './routes/courses.$classSlug.$subjectSlug'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiPaymentsVerifyRouteImport } from './routes/api/payments/verify'
import { Route as ApiPaymentsCreateOrderRouteImport } from './routes/api/payments/create-order'
import { Route as AdminMarketingNewsletterRouteImport } from './routes/admin/marketing.newsletter'
import { Route as AdminBlogsEditorRouteImport } from './routes/admin/blogs.editor'
import { Route as AuthenticatedLearnCourseIdRouteImport } from './routes/_authenticated/learn.$courseId'
import { Route as AuthenticatedEnrollCourseIdRouteImport } from './routes/_authenticated/enroll.$courseId'
import { Route as AuthenticatedEnrollSuccessCourseIdRouteImport } from './routes/_authenticated/enroll-success.$courseId'
import { Route as AuthenticatedDashboardProgressRouteImport } from './routes/_authenticated/dashboard_.progress'

const VsatRoute = VsatRouteImport.update({
  id: '/vsat',
  path: '/vsat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClassRoute = DemoClassRouteImport.update({
  id: '/demo-class',
  path: '/demo-class',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVsatRegistrationsRoute = AdminVsatRegistrationsRouteImport.update({
  id: '/vsat-registrations',
  path: '/vsat-registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveClassesRoute = AdminLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFixLessonsRoute = AdminFixLessonsRouteImport.update({
  id: '/fix-lessons',
  path: '/fix-lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesClassSlugSubjectSlugRoute =
  CoursesClassSlugSubjectSlugRouteImport.update({
    id: '/courses/$classSlug/$subjectSlug',
    path: '/courses/$classSlug/$subjectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsVerifyRoute = ApiPaymentsVerifyRouteImport.update({
  id: '/api/payments/verify',
  path: '/api/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateOrderRoute = ApiPaymentsCreateOrderRouteImport.update({
  id: '/api/payments/create-order',
  path: '/api/payments/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingNewsletterRoute =
  AdminMarketingNewsletterRouteImport.update({
    id: '/marketing/newsletter',
    path: '/marketing/newsletter',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogsEditorRoute = AdminBlogsEditorRouteImport.update({
  id: '/blogs/editor',
  path: '/blogs/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedLearnCourseIdRoute =
  AuthenticatedLearnCourseIdRouteImport.update({
    id: '/learn/$courseId',
    path: '/learn/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnrollCourseIdRoute =
  AuthenticatedEnrollCourseIdRouteImport.update({
    id: '/enroll/$courseId',
    path: '/enroll/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnrollSuccessCourseIdRoute =
  AuthenticatedEnrollSuccessCourseIdRouteImport.update({
    id: '/enroll-success/$courseId',
    path: '/enroll-success/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProgressRoute =
  AuthenticatedDashboardProgressRouteImport.update({
    id: '/dashboard_/progress',
    path: '/dashboard/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/fix-lessons': typeof AdminFixLessonsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/admin/blogs/editor': typeof AdminBlogsEditorRoute
  '/admin/marketing/newsletter': typeof AdminMarketingNewsletterRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/fix-lessons': typeof AdminFixLessonsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/admin/blogs/editor': typeof AdminBlogsEditorRoute
  '/admin/marketing/newsletter': typeof AdminMarketingNewsletterRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo-class': typeof DemoClassRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vsat': typeof VsatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/fix-lessons': typeof AdminFixLessonsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/vsat-registrations': typeof AdminVsatRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/dashboard_/progress': typeof AuthenticatedDashboardProgressRoute
  '/_authenticated/enroll-success/$courseId': typeof AuthenticatedEnrollSuccessCourseIdRoute
  '/_authenticated/enroll/$courseId': typeof AuthenticatedEnrollCourseIdRoute
  '/_authenticated/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/admin/blogs/editor': typeof AdminBlogsEditorRoute
  '/admin/marketing/newsletter': typeof AdminMarketingNewsletterRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/courses/$classSlug/$subjectSlug': typeof CoursesClassSlugSubjectSlugRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/fix-lessons'
    | '/admin/lessons'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/dashboard/progress'
    | '/enroll-success/$courseId'
    | '/enroll/$courseId'
    | '/learn/$courseId'
    | '/admin/blogs/editor'
    | '/admin/marketing/newsletter'
    | '/api/payments/create-order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/courses/$classSlug/$subjectSlug'
    | '/admin/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/fix-lessons'
    | '/admin/lessons'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/dashboard/progress'
    | '/enroll-success/$courseId'
    | '/enroll/$courseId'
    | '/learn/$courseId'
    | '/admin/blogs/editor'
    | '/admin/marketing/newsletter'
    | '/api/payments/create-order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/courses/$classSlug/$subjectSlug'
    | '/admin/blogs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/demo-class'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/vsat'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/contact-messages'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/enrollments'
    | '/admin/fix-lessons'
    | '/admin/lessons'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/vsat-registrations'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/_authenticated/dashboard_/progress'
    | '/_authenticated/enroll-success/$courseId'
    | '/_authenticated/enroll/$courseId'
    | '/_authenticated/learn/$courseId'
    | '/admin/blogs/editor'
    | '/admin/marketing/newsletter'
    | '/api/payments/create-order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/courses/$classSlug/$subjectSlug'
    | '/admin/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DemoClassRoute: typeof DemoClassRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VsatRoute: typeof VsatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPaymentsCreateOrderRoute: typeof ApiPaymentsCreateOrderRoute
  ApiPaymentsVerifyRoute: typeof ApiPaymentsVerifyRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  CoursesClassSlugSubjectSlugRoute: typeof CoursesClassSlugSubjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsat': {
      id: '/vsat'
      path: '/vsat'
      fullPath: '/vsat'
      preLoaderRoute: typeof VsatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-class': {
      id: '/demo-class'
      path: '/demo-class'
      fullPath: '/demo-class'
      preLoaderRoute: typeof DemoClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vsat-registrations': {
      id: '/admin/vsat-registrations'
      path: '/vsat-registrations'
      fullPath: '/admin/vsat-registrations'
      preLoaderRoute: typeof AdminVsatRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-classes': {
      id: '/admin/live-classes'
      path: '/live-classes'
      fullPath: '/admin/live-classes'
      preLoaderRoute: typeof AdminLiveClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fix-lessons': {
      id: '/admin/fix-lessons'
      path: '/fix-lessons'
      fullPath: '/admin/fix-lessons'
      preLoaderRoute: typeof AdminFixLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$classSlug/$subjectSlug': {
      id: '/courses/$classSlug/$subjectSlug'
      path: '/courses/$classSlug/$subjectSlug'
      fullPath: '/courses/$classSlug/$subjectSlug'
      preLoaderRoute: typeof CoursesClassSlugSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/verify': {
      id: '/api/payments/verify'
      path: '/api/payments/verify'
      fullPath: '/api/payments/verify'
      preLoaderRoute: typeof ApiPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create-order': {
      id: '/api/payments/create-order'
      path: '/api/payments/create-order'
      fullPath: '/api/payments/create-order'
      preLoaderRoute: typeof ApiPaymentsCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing/newsletter': {
      id: '/admin/marketing/newsletter'
      path: '/marketing/newsletter'
      fullPath: '/admin/marketing/newsletter'
      preLoaderRoute: typeof AdminMarketingNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/editor': {
      id: '/admin/blogs/editor'
      path: '/blogs/editor'
      fullPath: '/admin/blogs/editor'
      preLoaderRoute: typeof AdminBlogsEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/learn/$courseId': {
      id: '/_authenticated/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enroll/$courseId': {
      id: '/_authenticated/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/enroll/$courseId'
      preLoaderRoute: typeof AuthenticatedEnrollCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enroll-success/$courseId': {
      id: '/_authenticated/enroll-success/$courseId'
      path: '/enroll-success/$courseId'
      fullPath: '/enroll-success/$courseId'
      preLoaderRoute: typeof AuthenticatedEnrollSuccessCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard_/progress': {
      id: '/_authenticated/dashboard_/progress'
      path: '/dashboard/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof AuthenticatedDashboardProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDashboardProgressRoute: typeof AuthenticatedDashboardProgressRoute
  AuthenticatedEnrollSuccessCourseIdRoute: typeof AuthenticatedEnrollSuccessCourseIdRoute
  AuthenticatedEnrollCourseIdRoute: typeof AuthenticatedEnrollCourseIdRoute
  AuthenticatedLearnCourseIdRoute: typeof AuthenticatedLearnCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDashboardProgressRoute: AuthenticatedDashboardProgressRoute,
  AuthenticatedEnrollSuccessCourseIdRoute:
    AuthenticatedEnrollSuccessCourseIdRoute,
  AuthenticatedEnrollCourseIdRoute: AuthenticatedEnrollCourseIdRoute,
  AuthenticatedLearnCourseIdRoute: AuthenticatedLearnCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminFixLessonsRoute: typeof AdminFixLessonsRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminLiveClassesRoute: typeof AdminLiveClassesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminVsatRegistrationsRoute: typeof AdminVsatRegistrationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsEditorRoute: typeof AdminBlogsEditorRoute
  AdminMarketingNewsletterRoute: typeof AdminMarketingNewsletterRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminFixLessonsRoute: AdminFixLessonsRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminLiveClassesRoute: AdminLiveClassesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminVsatRegistrationsRoute: AdminVsatRegistrationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsEditorRoute: AdminBlogsEditorRoute,
  AdminMarketingNewsletterRoute: AdminMarketingNewsletterRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DemoClassRoute: DemoClassRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VsatRoute: VsatRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPaymentsCreateOrderRoute: ApiPaymentsCreateOrderRoute,
  ApiPaymentsVerifyRoute: ApiPaymentsVerifyRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  CoursesClassSlugSubjectSlugRoute: CoursesClassSlugSubjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
